name: 'ggshield scan'
description: 'Scan commits for hardcoded secrets and security policy breaks.'
author: GitGuardian <support@gitguardian.com>

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  args:
    description: |
      Arguments to pass to `ggshield secret scan ci`.

      [`ggshield secret scan ci` reference](https://docs.gitguardian.com/ggshield-docs/reference/secret/scan/ci).
    required: false

runs:
  using: 'docker'
  image: 'docker://gitguardian/ggshield:v1.32.1'
  entrypoint: '/app/docker/actions-secret-entrypoint.sh'
  args:
    - ${{ inputs.args }}
